### PR TITLE
chunky style fixes

### PR DESCRIPTION
**Pull request by ZeroChaos-**
lib/blue_hydra/btmon_handler.rb changes are to handle newer bluez which changes a few things at startup that we want to ignore.

The rest of the changes are to reject obviously bad chunks so we don't parse them.  Added a mechanism to deal with logging the bad chunks so we can fix whatever is wrong.

### CODE REVIEW

**Comment by granolocks** [comment]
yay

**Comment by dallaswinger** [comment]
ack

**Comment by dallaswinger** [comment]
afaic this is better than a device being 47 different devices. lets merge and test across everythin

**Comment by granolocks** [comment]
LGTM on a deeper review

**Pull request merged**
