### PR TITLE
Add `ruby-dev` note to README.md

### PR DESCRIPTION
**Pull request by bclune**

### CODE REVIEW

**Comment by granolocks** [comment]
ACK

**Comment by ZeroChaos-** [comment]
Should have added to line 30.... It was even obvious from the diff :-P

**Comment by bclune** [comment]
It's not a Bluetooth package and I felt there was value in separating Ruby concerns from Bluetooth tools. Otherwise we should add e.g. `ruby-2.0` to the list of packages in the `apt-get` string.

**Comment by ZeroChaos-** [comment]
ruby, not ruby-2.0, but yeah, feel free to add it

**Pull request merged**
