### PR TITLE
we were pulling in constantly changing data and then adding it to a f…

### PR DESCRIPTION
**Pull request by ZeroChaos-**
…ield, causing the field to grow until overflow and error which crushed the logs. we might want to track last value, but not sure it's worth it

### CODE REVIEW

**Comment by ZeroChaos-** [comment]
Kevin was complaining about ~4GB logs.  This value was overflowing the 65535 limit and spewing the whole thing into the logs pretty often.  Probably need to reset the db for a few customers, might  consider an automated migration to take care of it....

**Comment by granolocks** [comment]
LGTM

**Comment by ZeroChaos-** [comment]
**DB before this PR**
zero@gato blue_hydra % echo "SELECT le_service_uuids FROM blue_hydra_devices;" | sqlite3 -column blue_hydra.db                                                        (git)-[big_logs] 
["Vendor specific (d2d3f8ef-9c99-4d9c-a2b3-91c85d44326c)"]
["(UUID 0xfe9f): 0000000000000000000000000000000000000000"
["Vendor specific (d2d3f8ef-9c99-4d9c-a2b3-91c85d44326c)"]
["Vendor specific (abc24206-9bd7-034f-4fc9-ed10232c4bf4)"]
                                                          
["Vendor specific (abc24206-9bd7-034f-4fc9-ed10232c4bf7)"]

**RUN**
zero@gato blue_hydra % sudo bin/blue_hydra --daemon                                                                                                                   ^C%                                                                                                                                                                                     

**DB after cleanup caused by this PR**
zero@gato blue_hydra % echo "SELECT le_service_uuids FROM blue_hydra_devices;" | sqlite3 -column blue_hydra.db                                                        (git)-[big_logs] 
["Vendor specific (d2d3f8ef-9c99-4d9c-a2b3-91c85d44326c)"]
["Unknown (0xfe9f)"]                                      
["Vendor specific (d2d3f8ef-9c99-4d9c-a2b3-91c85d44326c)"]
["Vendor specific (abc24206-9bd7-034f-4fc9-ed10232c4bf4)"]
                                                          
["Vendor specific (abc24206-9bd7-034f-4fc9-ed10232c4bf7)"]
["Unknown (0x3e10)","Vendor specific (6a4e3e10-667b-11e3-9

**Comment by granolocks** [comment]
sure ack if tested

**Pull request merged**
