### PR TITLE
this seems to be closer to what we actually use

### PR DESCRIPTION
**Pull request by ZeroChaos-**

### CODE REVIEW

**Comment by ZeroChaos-** [comment]
"data_mapper" is a meta gem, but it looks like the only thing in there which we need is dm-migrations so let's just dep on the right thing.

**Comment by ZeroChaos-** [comment]
tested and confirmed functional

**Comment by ZeroChaos-** [comment]
do hold merge on this for now though, needs deeper testing, but it's closer to correct, probably still missing dm-validations or something like that.

**Comment by ZeroChaos-** [comment]
passes rspec on a clean gentoo install with only the specified deps installed.

oh, and it runs too.

**Comment by granolocks** [comment]
go for it

**Pull request merged**
